### ISSUE TITLE
Sometimes "ghosts" of players are appearing

### ISSUE THREAD

**Issue by s0me-1** [vram4/Ogar#13]
They are not moving, and they disappears after a few seconds ^^

Using official Client ;)

**Comment by Toumaniere** [comment]
The same with this client : http://game.agario.org/
Plus sometimes there is ghost food :o

**Comment by Ephemerality** [comment]
The agario.org client is just a stolen & bastardized version of the (up to date) original, so I'm not surprised if it experiences the same problems.  
Issue is probably due to the new update packet, which contains a list of cells to delete instead of the currently active ones. I'll look at it when I'm off work if vram4 doesn't beat me to it.

**Comment by s0me-1** [comment]
Here's a GIF of the problem :)
http://gyazo.com/367dde191cc7ec35cdef5c544e9484f3

**Comment by Ephemerality** [comment]
Might be something with collisions as well, Fallus seems to be an active player and should have been eatable...

**Comment by s0me-1** [comment]
Fallus is also the yellow ball on the left, as you can see, only the big ball is moving ;)

**Comment by Ephemerality** [comment]
Ah, the big one is moving. Gotcha.

**Comment by vram4** [comment]
Use the latest version of the client and the server please.

**Comment by s0me-1** [comment]
Just to be sure, witch client are you talking about ?

**Comment by vram4** [comment]
The official client, not the agario.org one.

**Comment by s0me-1** [comment]
Well the gif was recorded using your last commit and the agar.io client :/

**Comment by vram4** [comment]
Make sure you are using the master branch, not legacy branch

**Comment by s0me-1** [comment]
Yes we're sure, this is strange, because we're getting no error in the client console :/

**Comment by Ephemerality** [comment]
Still at work so I haven't had a chance to look into detail how we're handling it, but are we only sending the destroynodes when a node is eaten or is it sending a list of previously-visible nodes that are no longer on screen as well?
Killed nodes are automatically destroyed, so that covers them. In my C# version I have a visible nodes list for the client and when the screen is updated, it takes the difference of the new and old lists and sends them in the destroynodes portion of the update...

**Comment by Ephemerality** [comment]
Pushing a change now that seems to work in my limited testing. vram4 feel free to revert/change/tweak as necessary.

**Comment by vram4** [comment]
Yeah, the "ghost" cells you still see are still in the world, just not at that location. Anyways, i pushed an update to fix it.

**Comment by s0me-1** [comment]
Still happening with your latest commit and official client, on a new server :
http://gyazo.com/5741af3e8b2f97b3aa362933b7d0bdb2

**Comment by vram4** [comment]
I pushed an update that should fix this issue.
