### ISSUE TITLE
"Cannot find module Ogar"

### ISSUE THREAD

**Issue by natinusala** [vram4/Ogar#25]
Hi,

I just went to `/var/` and copyed-pasted every step you provide in the README in order to install Ogar on my Debian installation. When I do `node Ogar` it says `Error: Cannot find module '/var/Ogar'`... so I 
don't really know what to do...

Could you help me ? Thanks !

**Comment by s0me-1** [comment]
cd Ogar
node src

--- Message initial ---

De : "natinusala" <notifications@github.com>
Envoyé : 9 juin 2015 21:01
A : "vram4/Ogar" <Ogar@noreply.github.com>
Objet : [Ogar] "Cannot find module Ogar" (#25)

Hi,

I just went to `/var/` and copyed-pasted every step you provide in the README in order to install Ogar on my Debian installation. When I do `node Ogar` it says `Error: Cannot find module '/var/Ogar'`... so I
don't really know what to do...

Could you help me ? Thanks !

---
Reply to this email directly or view it on GitHub:
https://github.com/vram4/Ogar/issues/25

**Comment by vram4** [comment]
Try cloning with my fork:

git clone git://github.com/vram4/Ogar.git Ogar
npm install ./Ogar
node Ogar

**Comment by natinusala** [comment]
It works with `node src` thanks :)
