### ISSUE TITLE
Spectators not kicked when Hunger Games are over

### ISSUE THREAD

**Issue by M64mc** [vram4/Ogar#49]
This project is really amazing. I love playing Hunger Games with friends.
I'm kinda happy I stumbled upon this.

I just spectated some bots playing Hunger Games on my server.
When one won, I wasn't kicked while spectating.

Additionally, if you click Play while the game is in progress, you just sit there. Is there any way to prevent joining if the game is running?
The last thing I noticed is that the countdown counts in steps of 2 (10 - 8 - 6 - ...).

I also got a question: What does the master server do?

**Comment by vram4** [comment]
Hey man, Im glad youre enjoying this. I havent added code that would kick spectators after a game end, because you can press "q" to switch players., same for players try to join while a game is in progress. Also the countdown should be counting down each second now but i havent tested that yet.

The master server is for people who want to auto connect to the game server without needing to enter in the ip.

**Comment by M64mc** [comment]
Thanks!

How do you use the master server?
Will it be a web page that will open agar.io and connect to the server?
And why does it say "127.0.0.1:443"?

**Comment by vram4** [comment]
The master server is not properly implemented yet
