### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fantastiic** [vram4/Ogar#55]
Is it possible to make custom cells? Like the virus are spiked. Or is this client-sided?

**Comment by vram4** [comment]
Yes, its very easy but you have to modify a few files. I might make a full tutorial later.

Heres some steps for a basic tutorial (replace the values in brackets):
1. Edit an existing gamemode (like FFA) or create a new one. 
2. Add the following code at the bottom of the file:
```javascript
var Cell = require('../entity/Cell'); // This will import the base of the cell class

function [Cell Name]() { // Cell class
    Cell.apply(this, Array.prototype.slice.call(arguments)); // This is the super constructor

    this.cellType = 4; // Random cell type id
    this.color = {r: 0, g: 0, b: 200}; // Blue color as an example
    this.spiked = 1; // Setting this value to 1 will make the cell appear with spiked
}

[Cell Name].prototype = new Cell();
```
3. Now that code makes your own cell, but it doesnt do anything to the game world though. To make it spawn randomly were going to add this code so that it spawns one instance of this cell when the server starts.
```javascript
[Gamemode Name].prototype.onServerInit = function(gameServer) {
    gameServer.run = true;
    var mycell = new [Cell Name](gameServer.getNextNodeId(), null, gameServer.getRandomPosition(), [Mass]);
};
```
The parameters for creating a cell are as follows:
1. Node id - A unique id for each cell
2. Cell's owner - For player cells, this value is null in our case because no one owns this cell
3. Starting position of the cell - We get a random position in our case
4. Starting mass

There are other ways you can add in a cell, but i figured this was the easiest.

**Comment by fantastiic** [comment]
I see, but is there any way to change its form?

**Comment by vram4** [comment]
If youre talking about the spikes, you can just change "this.spiked" to 1. But the shape will always be a circle.

**Comment by fantastiic** [comment]
Oh so it's impossible to make a square? That'd be very useful for other custom game modes

**Comment by vram4** [comment]
Yeah its impossible for now. Maybe in the future Zeach will add something to the client.

**Comment by fantastiic** [comment]
That's client-sided then, I see, all we can do is wait then ^^ thx for answering tho =)
