### ISSUE TITLE
agar.io client update

### ISSUE THREAD

**Issue by tdmusic** [vram4/Ogar#87]
What appears to be an update to the agar.io client has now stopped http://agar.io/?IP:PORT from now working. any pointers for the right direction with a client?

**Comment by Eureka22** [comment]
You can download the client code and deploy it on your server.

You can use mine if you want. 
https://github.com/Eureka22/agar-clone.git

don't forget to replace the ip in main_out.js with your server's ip and port.

**Comment by tdmusic** [comment]
Legend! If i can be of any assistance please, let me know.

**Comment by joery1337** [comment]
@Eureka22 Sorry but most of your function names etc. make no sense..

**Comment by Eureka22** [comment]
@joery1337 I am working on this now. It can take some time. Because the client of Agar.io used packed js code.

**Comment by tdmusic** [comment]
Thanks for the client source, works amazingly well. Any information with regards to get multiple game modes working on both the server and the client end?

**Comment by Eureka22** [comment]
@tdmusic I am not sure. I think the client should support multiple game mode now.

**Comment by tdmusic** [comment]
@Eureka22 - Cheers, love the custom skin support and everything. How are you doing the chat, i assumed it'd have to be enabled on the server too?

**Comment by Eureka22** [comment]
Yes I am going to use ws to do the chatting, it's not complicated. I would prefer using another chat server than integrating it into @vram4 's server side at this moment. If it works fine, I might consider adding it to the server side.

**Comment by tdmusic** [comment]
@Eureka22 Server side would be cool, with regards to the custom skins, is it a matter of just uploading it to the skins folder and it should work?

**Comment by Eureka22** [comment]
@tdmusic A little bit complicated than that. On the one hand is uploading, on the other hand, the client side request the server side to check if there is new skin uploaded every 15 seconds and add it to knownNameDict. And as such, they can be rendered on the client side. 

I would write it in readme soon. The fun thing after I supported custom skin is that some players tried to use a screenshot of the background as skin to make themselves "invisible".

**Comment by tdmusic** [comment]
Just removed the upload ability as i thought something like that may happen! Need to make a way to vet them (maybe put the images in one dir and then move them over when you approve them?)

**Comment by Eureka22** [comment]
Good idea.

**Comment by modsfabio** [comment]
Working client: http://agar.modszombies.com

**Comment by tdmusic** [comment]
Yeah i got mine working too:

www.thelol.party

What I'm trying to work on now is linking the client with the different game modes that the new branch allows us to do.

**Comment by joery1337** [comment]
Custom skins is the worst idea ever..

**Comment by tdmusic** [comment]
@joery1337 not really sure why? I've just removed the option to upload, no i can just add skins i want.

**Comment by joery1337** [comment]
@tdmusic uploading skins I meant, you would only get porn skins, dead animals etc.

**Comment by Eureka22** [comment]
@tdmusic was right, censorship and regulation is required if we allow custom skins. But it's more fun I guess.

**Comment by vram4** [comment]
Yes, Zeach changed it, but you can connect by going to agar.io, letting the page load, then in your address bar replace
> agar.io
with
>javascript:connect("ws://127.0.0.1")
then press enter

**Comment by JBoughter** [comment]
Then in that case @vram4 you should change the readme to reflect this change. :)

**Comment by vram4** [comment]
@JBoughter It is updated on the master-server-pre-release branch, i dont want to update it on the master branch as that would create merging problems and i hate dealing with those.

**Comment by tdmusic** [comment]
Made me worry if my dedicated server was screwing up on ports again! I needed to move to a custom client anyway!

**Comment by Eureka22** [comment]
@vram4 In that case every single player need to do that JavaScript stuff. Do you think that would be annoying?

**Comment by tdmusic** [comment]
@Eureka22 Not much he can really do, if the main clients changed then we'll just have to manage.

**Comment by vram4** [comment]
@Eureka22 @tdmusic Yeah its either that or get a mod for connection.

**Comment by vram4** [comment]
@tdmusic Also, to answer your question about multiple gamemodes, that has been fixed (server side) on the latest commit. To add your server to the gamemode listing, simply add ```:[name of gamemode]``` to your region name. So if i wanted to add a teams server, i would type:
```
add US-Fremont:teams
```
in the console. Alternatively, you can also go into the config file and add ```"US-Fremont:teams",1,``` to the regions value (make sure its behind the brackets)

**Comment by tdmusic** [comment]
@vram4 Thanks, need to work on how to get it working on the client now.

**Comment by vram4** [comment]
@tdmusic Assuming youre using the default client, you wont need to do anything.

**Comment by tdmusic** [comment]
@vram4 Hm, will give it a go now, just need to update my server files, cheers.

**Comment by tdmusic** [comment]
@vram4 Having invalid commands (have downloaded from the new branch)

**Comment by vram4** [comment]
@tdmusic Make sure you select the master server with "select 0"

**Comment by Eureka22** [comment]
@tdmusic @joery1337 refactoring the client code is almost done with the help of @m-byte It should not be too hard to understand the code and add new features to that. :)

**Comment by tdmusic** [comment]
@Eureka22 Sounds good!

@vram4 still get an invalid command, none of the new commands work.

**Comment by tdmusic** [comment]
Ah wait, i see what I'm doing now, didn't bother checking the actually SCR, sorry!

**Comment by maixuanhan** [comment]
If you want to play with the Vanilla client, the **connect** method in Console is still working.
*connect('ws://IP:PORT')*
[swarm-ogar](https://github.com/giantswarm/swarm-ogar)

or else call it as a javascript function right in the address bar like @vram said.

**Comment by m-byte** [comment]
@vram4 I decided to change the protocol version for our client. Now, Ogar can detect which client it is talking to. At the moment, the server can use this to send custom text without numbers to the leaderboard by using package id 48 (as this is used by Ogar internally).

I was thinking, that this could be used to implement live chat in Ogar for clients supporting this in the next version of our client.

The changes are documented in both @Eureka22 and my repo.

**Comment by tdmusic** [comment]
@m-byte A live chat would add so much more playability to the game! Great work!

**Comment by m-byte** [comment]
Since our reverse engineered files obviously still contain the original code with unknown license, I decided to start a new project called `Ogar-client`. This one is released under the Apache 2.0 license. I am not really that interested in things like the wobbly cells, so graphically, it might be a bit more basic until someone decides to step up and implement that part.

Right now, I already have the overlays (the main dialog looks almost identical to the agar.io one, as it is also using bootstrap). There is also a dialog for uploading custom skins.
Most of the javascript is still on my todo-list. If anyone is interested in contributing, you are very welcome to do so ;)

**Comment by Eureka22** [comment]
@m-byte Good idea, I am willing to contribute after I finish agar-clone. However I am afraid that Ogar-client does not help much on the license stuff since it seems that it still violate the Terms of Agario. 

As you can find in the [Terms](http://agar.io/terms.txt). I am not a law expert so and one understand this can explain it to us. 

>
Intellectual Property Rights
You may not use any IPRs in the Site or Agar.io Game for any purpose or in any manner whatsoever that is not authorised by the copyright owner.
Further, you may not:
*	use the Agario icon, the word AGARIO, or any similar words on your website without the prior written consent of Agario;
*	use the words AGARIO, or any similar words in the domain name for your website;
*	use the layout of the Site or the Agario Game on any website; 
*	link to the Site or establish a link in such a way as to suggest any form of association, approval or endorsement on our part where none exists; or
*	copy any aspect of the Agar.io Game which includes but is not limited to the shape of the cells, the gameplay mechanics, designs, graphics, features and the default colour scheme available for any aspect of the Agar.io Game. 

> All other intellectual property subsisting (now or in the future) in the Site is owned by their respective owners. You may not use any such intellectual property for any purpose or in any manner that is not authorised by its owner. If you use any of our IPRs or any intellectual property of a third party available on the Site in a way that is not specifically authorised by these Terms and Conditions, your right to use the Site will cease immediately and we reserve the right to take legal action against you.

**Comment by m-byte** [comment]
From my point of view, especially the third part should not be enforceable under pretty much any jurisdiction, as the site is based on bootstrap. But let's just go through them:
- 1-2 are about agario, agar.io, etc. That's not a problem for us, since we are using the name Ogar.
- 3 as I wrote above, the design is a standard bootstrap design. Bootstrap is definitely not their IP. Twitter released it under the MIT license. No problem for us.
- 4 we are not linking to their site.
- 5 the client isn't actually doing most of the characteristic features. If it ever came to that, we would probably only have to change the shape of the cells. Everything else is mostly done on the server.

Apart from that, the last sentence is interesting. The worst thing that could happen would be being banned from their site and possibly receiving a cease and desist letter.

However, with an untainted code base, the change to a different shape of cells would most likely be enough.

Still, IANAL...

**Comment by s0me-1** [comment]
Hi, I'm just leaving a message to tell that I already have a Client wich support multi-servers, customs skins, and Tags ( Eg : "Belgium | Nick" as nickname will return the Belgium skin). You can test it here.

Fully translated to French because our servers was intended for Belgian students, but feel free to test it here :
agario.toum.ovh/client/

If I can help, let me know :)

**Comment by Ephemerality** [comment]
If you get a 'Cannot read property 'length' of undefined' when you try to do connect("ws://ip:port") in the java console, try 'connect("ws://ip:port", "")' instead.
