### ISSUE TITLE
Brainstorm for new features

### ISSUE THREAD

**Issue by Eureka22** [vram4/Ogar#94]
As most of the project it finished, why don't we brainstorm some new features that would add fun to this game? 

I would like to start with "evolving AI", that the AI bot will learn from its success and failures, and also learn from the players. Use a mechanism like genetic algorithm to evolve generation by generation. 

Do you guys have other cool ideas?

**Comment by vram4** [comment]
Actually, I plan on rewriting the AI code after i finish work on my own client (coded in java). Stuff like server stability comes first though.

**Comment by Eureka22** [comment]
@vram4 Very cool, I am working on the stability too. I am collecting logs and calling on players to test. (About the memory leak). 

The client is a big headache though. Although our reverse engineered client allow me to add new features to do that, I found it actually violates the terms of agario. What's more, according to them, any third-party client is not allowed even implemented in another language. So I am worried about that. What do you think about that?

**Comment by vram4** [comment]
@Eureka22 Yeah, i know about those rules, but the main reason why im writing my own client is because my computer is crap and agar.io on the browser lags on vanilla servers (especially US East), while on my client, it doesnt lag at all. I understand why Zeach would make those rules though, he cant make money if people use their own clients, because of that, i wont be releasing my client to the public.

**Comment by batbug** [comment]
I think it needs a chat

**Comment by tdmusic** [comment]
Chat for definite, most of these clones violate the terms..

**Comment by Eureka22** [comment]
Just finished the chat feature. @tdmusic @vram4 by adding a few lines to server side. It works well with my client. 

![image](https://cloud.githubusercontent.com/assets/5158896/8327532/c41e94fa-1a9b-11e5-87cc-f42b5f6ef2df.png)

**Comment by batbug** [comment]
Wow. Looks pretty good. Are you planning on sharing this?

**Comment by Eureka22** [comment]
@batbug Yes after I clean up the code a little bit. You can also find that in my Ogar repo and agar-clone repo.

**Comment by batbug** [comment]
Yep.  I checked. Seems to be pretty neat. Especially the server-side!

**Comment by rocher77** [comment]
Ideas for game - 
barrier blobs that you cant go through, so you can block bigger blobs
different shaped areas, like a circle so you cant get pushed into corners
Power ups, that give different effects

Other ideas - 
an offline client, for when you dont have internet so you can play at a LAN

**Comment by m-byte** [comment]
@rocher77 regarding that last point, you might want to take a look at Eureka22/agar-clone and m-byte/Ogar-client

@Eureka22 @batbug I played with the structure of the chat messages, which resulted in this: https://github.com/Eureka22/Ogar/pull/1

**Comment by Eureka22** [comment]
@m-byte Thanks! The new version looks great, we can not only send chat, but also broadcast system messages with that flag added.

**Comment by vram4** [comment]
@Eureka22 I would prefer to keep the features of Ogar limited to things that can be achieved with the vanilla clients. That being said, im thinking about implementing a custom plugin system so that people can add in their own features if they modded the client.

**Comment by m-byte** [comment]
@vram4 That's why we are using the version bytes at the start of a connection. That way, a server can detect what kind of client it is talking to. Packet 255 is either 673720361 for vanilla or 1332175218 for extended clients. We still have to add a function to check which client it is, but as soon as that is done, I don't see why this could not be merged with Ogar.

Btw: the inspiration for packet 48 came from the the packet id you used in UpdateLeaderboard.js. Once the client version is stored in the PlayerTracker, the if statement only has to be uncommented and `client` has to be replaced by the proper name of the variable. Then, the server will display every leaderboard on every client. The only difference is, that the vanilla client will display numbers in front of the `custom text` leaderboard.

As for the chat feature: From my point of view, that is pretty simple. On the vanilla client, these packets are simply ignored. And who knows, if this feature works well with Ogar and our clients, maybe it gets introduced into the vanilla client in a future version...

**Comment by m-byte** [comment]
Regarding a new feature: how about [oddball](http://halo.wikia.com/wiki/Oddball)? There will be a food cell called ball or something (should probably be blocked as nick for players trying to connect). Eating the ball decreases your size to the average (excluding your own mass) size on the server (if your size is smaller, it stays the same). The leaderboard is ordered by the time a player/team was able to hold the ball.
This could be made either as a team or as a ffa game...

**Comment by m-byte** [comment]
Another game would be a zombie-type... Whenever you get "eaten" by a zombie, you turn into a zombie (gray). Obviously, zombies are in a team and can't eat each other.
A possible variation of this would be to have all zombies grow by the size of any new zombie. That way, it gets a lot harder to stay alive for a long time.

**Comment by batbug** [comment]
i suggest making zombie mode time-based. Two teams. Zombies have to "eat" everyone (turn into zombies) and people have to eat zombies. No respawns.

**Comment by batbug** [comment]
But either way, if zombies cannot eat each other, the people will have a simple way of winning -just feed themselvez to the biggest human and this players will eat every zombie. Too easy.
